 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: geometry                                                    
     # Surfaces =   5
     # Strips   = 100
     # Vortices =2000

  Sref =  144.00       Cref =  6.0000       Bref =  24.000    
  Xref =  7.5000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.15818     pb/2V =   0.00000     p'b/2V =   0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =   0.00000     r'b/2V =   0.00000

  CXtot =  -0.21416     Cltot =   0.00029     Cl'tot =  -0.00004
  CYtot =  -0.00171     Cmtot =   0.00821
  CZtot =   0.00806     Cntot =   0.00898     Cn'tot =   0.00899

  CLtot =   0.00001
  CDtot =   0.21432
  CDvis =   0.03000     CDind =   0.18432
  CLff  =  -0.00730     CDff  =   0.00058    | Trefftz
  CYff  =  -0.00174         e =    0.0077    | Plane  
 
 
 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   7.418206    CLb =   0.044292
 y  force CY |    CYa =  -0.286084    CYb =  -0.507288
 x' mom.  Cl'|    Cla =  -0.245480    Clb =  -0.032437
 y  mom.  Cm |    Cma =  -5.591677    Cmb =   0.010822
 z' mom.  Cn'|    Cna =   2.741168    Cnb =   0.309593

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.140609    CLq =  12.094331    CLr =  -0.029069
 y  force CY |    CYp =   0.149294    CYq =  -0.328518    CYr =   0.623848
 x' mom.  Cl'|    Clp =  -0.315331    Clq =  -0.397962    Clr =   0.056806
 y  mom.  Cm |    Cmp =   0.532038    Cmq = -14.855885    Cmr =  -0.077374
 z' mom.  Cn'|    Cnp =   0.814922    Cnq =   3.177419    Cnr =  -0.409879

 Neutral point  Xnp =  12.022665

 Clb Cnr / Clr Cnb  =   0.755986    (  > 1 if spirally stable )
